name: Build and Push Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - Dockerfile
  schedule:
    - cron: "0 8 * * TUE" # Every Tuesday at 8:00 AM UTC - We update the image weekly for security reasons
jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      BASE_IMAGE: "nginx:1.21-alpine"
      IMAGE: "BluetonicBeats/docker-google-fonts-proxy"
      LATEST_VERSION: "1.0"
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.0"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Github Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}

      - name: Prepare tags
        id: prep_tags
        shell: bash
        run: |
          if [[ "${{ matrix.version }}" == "${{ env.LATEST_VERSION }}" ]]; then
            TAGS="ghcr.io/bluetonicbeats/docker-google-fonts-proxy:latest,ghcr.io/bluetonicbeats/docker-google-fonts-proxy:${{ matrix.version }}"
          else
            TAGS="ghcr.io/bluetonicbeats/docker-google-fonts-proxy:${{ matrix.version }}"
          fi
          echo "VERSION_TAG=${{ matrix.version }}" >> $GITHUB_ENV
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.TAGS }}
          build-args: VERSION_TAG=${{ env.VERSION_TAG }}
