name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Build and public
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: citipo/docker-google-fonts-proxy
                  username: citipo
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  dockerfile: Dockerfile
